# Generated by Django 4.0.8 on 2022-12-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('HODep', 'head of department'), ('HODiv', 'head of division'), ('HOT', 'head of team'), ('Emp', 'employee')], default='Emp', max_length=5),
        ),
        migrations.AddField(
            model_name='team',
            name='min_attendance',
            field=models.CharField(choices=[(0.0, '0%'), (0.25, '25%'), (0.33, '33%'), (0.5, '50%'), (0.66, '66%'), (0.75, '75%'), (1.0, '100%')], default=1.0, max_length=2),
        ),
    ]
