# Generated by Django 4.0.8 on 2022-12-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employee_role_team_min_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='min_attendance',
            field=models.CharField(choices=[(0, '0%'), (25, '25%'), (33, '33%'), (50, '50%'), (66, '66%'), (75, '75%'), (100, '100%')], default=1.0, max_length=3),
        ),
    ]
